### ISSUE TITLE
Fix mismatch between priority queue numbers in simple_switch_CLI commands vs. P4 program priority value

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/project-ideas#6]
https://github.com/p4lang/behavioral-model/issues/1264

**Comment by jafingerhut** [comment]
@rizkyramadhana26 Would you be interested in working a fix for this issue, too?

**Comment by rizkyramadhana26** [comment]
Sure! This would be interesting, let me try.

**Comment by jafingerhut** [comment]
Closing, as this issue has been fixed by this PR: https://github.com/p4lang/behavioral-model/pull/1276
